env:
  browser: true
  es2021: true
extends:
  - react-app
  - react-app/jest
  - eslint:recommended
  - plugin:react/recommended
  - prettier
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules:
  react/react-in-jsx-scope: "off"
